from io import BytesIO
from xml.sax.saxutils import escape

from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import StreamingResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.controllers.pitch_controller import PitchController
from app.models.pitch import (
    CompetitorRequest,
    ExportRequest,
    PitchGenerationRequest,
    PitchIdRequest,
    SWOTRequest,
    ScoreRequest,
    ValuationRequest,
)

router = APIRouter(tags=["PitchForge AI"])


def _raise_if_failed(result: dict):
    if not result.get("success"):
        raise HTTPException(status_code=404, detail=result.get("error", "Request failed"))


def _paragraph(value) -> str:
    return escape(str(value or ""))


@router.post("/generate-pitch")
@router.post("/api/generate-pitch")
async def generate_pitch(request: PitchGenerationRequest):
    return PitchController.generate_pitch(
        request.startup_idea, request.industry, request.revenue_model
    )


@router.post("/generate-score")
@router.post("/generate-scores")
@router.post("/api/generate-score")
@router.post("/api/generate-scores")
async def generate_score(request: ScoreRequest):
    result = PitchController.generate_scores(request.pitch_id)
    _raise_if_failed(result)
    return result


@router.post("/generate-swot")
@router.post("/api/generate-swot")
async def generate_swot(request: SWOTRequest):
    result = PitchController.generate_swot(request.pitch_id)
    _raise_if_failed(result)
    return result


@router.post("/generate-competitors")
@router.post("/api/generate-competitors")
async def generate_competitors(request: CompetitorRequest):
    result = PitchController.generate_competitors(request.pitch_id)
    _raise_if_failed(result)
    return result


@router.post("/generate-valuation")
@router.post("/api/generate-valuation")
async def generate_valuation(request: ValuationRequest):
    result = PitchController.generate_valuation(request.pitch_id)
    _raise_if_failed(result)
    return result


@router.get("/pitch/{pitch_id}")
@router.get("/api/pitch/{pitch_id}")
async def get_pitch(pitch_id: str):
    result = PitchController.get_pitch_detail(pitch_id)
    _raise_if_failed(result)
    return result


@router.get("/history")
@router.get("/api/history")
async def get_history(limit: int = Query(10, ge=1, le=50), skip: int = Query(0, ge=0)):
    return PitchController.get_history(limit, skip)


@router.post("/export-pdf")
@router.post("/api/export-pdf")
async def export_pdf(request: ExportRequest):
    result = PitchController.get_pitch_detail(request.pitch_id)
    _raise_if_failed(result)
    pitch = result["data"]
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=54, leftMargin=54, topMargin=54)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="PitchTitle", parent=styles["Title"], textColor=colors.HexColor("#111827")))
    styles.add(ParagraphStyle(name="Section", parent=styles["Heading2"], textColor=colors.HexColor("#2563eb"), spaceBefore=12))
    story = [
        Paragraph(_paragraph(pitch["startup_name"]), styles["PitchTitle"]),
        Paragraph("Investor-ready startup pitch generated by PitchForge AI", styles["Normal"]),
        Spacer(1, 0.2 * inch),
    ]

    sections = [
        ("Elevator Pitch", pitch.get("elevator_pitch")),
        ("Problem Statement", pitch.get("problem_statement")),
        ("Solution", pitch.get("solution")),
        ("Business Model", pitch.get("business_model")),
        ("Market Opportunity", pitch.get("market_opportunity")),
        ("Investor Summary", pitch.get("investor_summary")),
    ]

    for title, body in sections:
        story.append(Paragraph(_paragraph(title), styles["Section"]))
        story.append(Paragraph(_paragraph(body), styles["BodyText"]))

    story.append(Paragraph("Revenue Streams", styles["Section"]))
    for item in pitch.get("revenue_streams", []):
        story.append(Paragraph(_paragraph(f"- {item}"), styles["BodyText"]))

    if pitch.get("scores"):
        score_rows = [["Metric", "Score"]]
        score_rows.extend(
            [
                ["Innovation", pitch["scores"].get("innovation_score")],
                ["Market Demand", pitch["scores"].get("market_demand_score")],
                ["Scalability", pitch["scores"].get("scalability_score")],
                ["Investor Appeal", pitch["scores"].get("investor_appeal_score")],
            ]
        )
        table = Table(score_rows, hAlign="LEFT", colWidths=[2.4 * inch, 1.2 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#d1d5db")),
                    ("PADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(Paragraph("Startup Score Engine", styles["Section"]))
        story.append(table)

    if pitch.get("valuation"):
        story.append(Paragraph("Valuation Estimate", styles["Section"]))
        valuation = pitch["valuation"]
        story.append(
            Paragraph(
                _paragraph(
                    f"Low: {valuation.get('low_estimate')} | Medium: {valuation.get('medium_estimate')} | High: {valuation.get('high_estimate')}"
                ),
                styles["BodyText"],
            )
        )
        story.append(Paragraph(_paragraph(valuation.get("reasoning", "")), styles["BodyText"]))

    doc.build(story)
    buffer.seek(0)
    filename = f"{pitch['startup_name'].replace(' ', '-')}-pitch.pdf"
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/api/health")
async def api_health():
    return {"status": "ok"}
